export const mockTickets = [
  {
    id: 1,
    title: "Login page not working",
    description: "Users are unable to login on mobile browsers. The submit button doesn't respond on iOS Safari.",
    status: "Open",
    priority: "High",
    assigned_to: "Agent A",
    created_by: "user1@test.com",
    created_at: "2025-07-01T10:00:00Z",
  },
  {
    id: 2,
    title: "Dashboard charts not loading",
    description: "The analytics charts on the dashboard show a blank white box instead of data.",
    status: "In Progress",
    priority: "Medium",
    assigned_to: "Agent B",
    created_by: "user2@test.com",
    created_at: "2025-07-02T12:30:00Z",
  },
  {
    id: 3,
    title: "Password reset email not received",
    description: "Multiple users reported they never receive the password reset email.",
    status: "Resolved",
    priority: "Critical",
    assigned_to: "Agent A",
    created_by: "user3@test.com",
    created_at: "2025-07-03T09:15:00Z",
  },
  {
    id: 4,
    title: "Export to PDF broken",
    description: "Clicking the Export PDF button throws a 500 error.",
    status: "Closed",
    priority: "Low",
    assigned_to: "Agent C",
    created_by: "user1@test.com",
    created_at: "2025-07-04T08:00:00Z",
  },
];